---
title: "chattr interface LLM pacakge for Rstudio/Positron."

execute:
  warning: false
  error: false
  
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    

---

chattr is an interface to LLMs (Large Language Models). It enables interaction with the model directly from RStudio and Positron. chattr allows you to submit a prompt to the LLM from your script, or by using the provided Shiny Gadget.


# install package

```{r}
pak::pak("mlverse/chattr")
```

# Load package

```{r}
library(chattr)
```

# Use package

```{r}
#copilot do not need OpenAI_API_KEY
my_chat <- ellmer::chat_github(model = "gpt-4o")
chattr_use(my_chat)
```
# using LLM as app

```{r}
#chattr_app()
```


# using LLM on code
```{r}
chattr("what is your name?")
```



```{r}
chattr_history=ch_history()
print(chattr_history)
```



# save history

```{r}
chat_file <- tempfile()
saveRDS(ch_history(), "chat_history.rds")
```


# clear history

```{r}
print(ch_history(list()))
```
# Re-load history

```{r}
chattr_history=ch_history(readRDS("chat_history.rds"))
print(chattr_history)

```



# reference

https://mlverse.github.io/chattr/

https://github.com/mlverse/chattr





